services:
  - type: web
    name: lumos-learning
    env: python
    repo: https://github.com/WarenBcs4/lumoslearner_Platform-LMS.git
    buildCommand: "cd lumos_learning && pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "cd lumos_learning && gunicorn lumos.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lumos-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: lumos-redis
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com

  - type: redis
    name: lumos-redis
    ipAllowList: []

databases:
  - name: lumos-db
    databaseName: lumos_learning
    user: lumos_user